apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
    # hard rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1d  # select 1 node az from instance nodes
          # - key: disktype
          #   operator: In
          #   values:
          #   - ssd  
    # soft rule
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop
      - weight: 10
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - amazon

  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
