apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
    # hard rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - ip-192-168-10-212.ec2.internal
            - ip-192-168-3-238.ec2.internal  # select 1 node az from instance nodes
          # - key: disktype
          #   operator: In
          #   values:
          #   - ssd  
    # soft rule
      # preferredDuringSchedulingIgnoredDuringExecution:
      # - weight: 1
      #   preference:
      #     matchExpressions:
      #     - key: project
      #       operator: In
      #       values:
      #       - roboshop
      # - weight: 10
      #   preference:
      #     matchExpressions:
      #     - key: project
      #       operator: In
      #       values:
      #       - amazon
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
