apiVersion: v1
kind: Pod
metadata:
  name: anti-affinity
spec:
  affinity:
    nodeAffinity:
    # hard rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - ip-192-168-10-212.ec2.internal
            - ip-192-168-3-238.ec2.internal  # select 1 node az from instance nodes
          # - key: disktype
          #   operator: In
          #   values:
          #   - ssd  

  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
