apiVersion: v1
kind: Pod
metadata:
  name: anti-affinity
spec:
  affinity:
    nodeAffinity:
    # hard rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: NotIn
            values:
            - us-east-1b  # select 1 node az from instance nodes
          # - key: disktype
          #   operator: In
          #   values:
          #   - ssd  

  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
